<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3453d95f-7227-49ee-8b9a-af609b453bfa</testSuiteGuid>
   <testCaseLink>
      <guid>706c3c74-00c5-4241-b7ad-a623b2131312</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>89684039-cda3-41f5-9743-536990ea3542</id>
         <masked>false</masked>
         <name>password</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/AM_Home/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9061b51b-3ada-4d66-a27f-0b147c06d11a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9061b51b-3ada-4d66-a27f-0b147c06d11a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>e3959707-e80e-4e71-92ae-d510e436c7ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9061b51b-3ada-4d66-a27f-0b147c06d11a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>89684039-cda3-41f5-9743-536990ea3542</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
