<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Asset</name>
   <tag></tag>
   <elementGuidId>73c38aab-248e-4b72-90b8-70fce37e263f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='searchDialogAssetTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchDialogAssetTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2714f548-c43f-43ed-8bd9-7ac1a8e789c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#assetPrefixNumbersActivity</value>
      <webElementGuid>aa20faed-4ce2-4760-87e4-0447cd508896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5950ed99-fbb8-48f3-b1af-eaeff3cc3ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDialogAssetTab</value>
      <webElementGuid>d2def64c-568c-40cc-9e77-a701e8eee650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asset #</value>
      <webElementGuid>2ccc21c0-0d10-431f-aae7-3dfa7e6c6643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDialogAssetTab&quot;)</value>
      <webElementGuid>7d1c7a0c-9ec8-439a-b999-c1dfa9bb3527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='searchDialogAssetTab']</value>
      <webElementGuid>ffb58bcb-4da9-44db-85ec-772e47ceb4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchDialog']/div/ul/li[3]/a</value>
      <webElementGuid>f46858a9-fe85-4b67-9306-73b4ba1c96d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Asset #')]</value>
      <webElementGuid>e6de4463-ab9d-48af-9f8b-18b3c1e81daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request #'])[2]/following::a[1]</value>
      <webElementGuid>3c6c660a-770e-421e-bf83-d2f60c9e665b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REZ Tracking #'])[2]/following::a[2]</value>
      <webElementGuid>2c4f70b4-12eb-4aed-b63d-3e2e6fbd73e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waybill #'])[1]/preceding::a[1]</value>
      <webElementGuid>bc268704-3578-4c96-bbd7-f07d5453df00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference #'])[2]/preceding::a[2]</value>
      <webElementGuid>499d2982-c301-4879-97c6-96c6832e9d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asset #']/parent::*</value>
      <webElementGuid>32effef6-7c64-4085-a632-50408530cfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#assetPrefixNumbersActivity')]</value>
      <webElementGuid>b19a382e-4733-44d1-a047-511fe050b4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>19f46b5f-431f-4e03-8fad-c1bb4f775cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#assetPrefixNumbersActivity' and @id = 'searchDialogAssetTab' and (text() = 'Asset #' or . = 'Asset #')]</value>
      <webElementGuid>2d926576-fe7b-4779-96ce-b17d2335f074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
