<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BOL</name>
   <tag></tag>
   <elementGuidId>93a95b86-ff25-4974-ab09-2cfc7826d329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='searchDialogBOLTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchDialogBOLTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8068a430-8469-49f9-ad74-b16690d08ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#billsOfLadingActivity</value>
      <webElementGuid>4ec0f959-b068-4396-a634-da5f23e82342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d175f6dc-f06c-41da-8492-581fedbea6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDialogBOLTab</value>
      <webElementGuid>6663bd66-7ff6-4f81-b6df-b0cf8afd3ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOL #</value>
      <webElementGuid>0a9aa9eb-0889-40c3-8122-4b1a3550083f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDialogBOLTab&quot;)</value>
      <webElementGuid>f0eb9e6d-968f-4bc1-8523-e360c5ad34a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='searchDialogBOLTab']</value>
      <webElementGuid>1d265514-bb2e-476d-8180-e4719b938992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchDialog']/div/ul/li[6]/a</value>
      <webElementGuid>0953f154-2bca-4df4-b58d-9ca4c19f2773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BOL #')]</value>
      <webElementGuid>1a84b214-5415-4285-ba1f-2d8fd4cdee59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference #'])[2]/following::a[1]</value>
      <webElementGuid>1ed0fa52-8e63-41cd-96c8-d39296606a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waybill #'])[1]/following::a[2]</value>
      <webElementGuid>a8b4110f-f036-472c-b6a4-bff55c7a8ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BOL #']/parent::*</value>
      <webElementGuid>e97cdec9-5591-4f8e-a846-3a9d769ebe70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#billsOfLadingActivity')]</value>
      <webElementGuid>395a2604-f23e-4ad3-bc79-8fd78f4b62a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[6]/a</value>
      <webElementGuid>def01468-def0-4a61-ba4a-bd4168294ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#billsOfLadingActivity' and @id = 'searchDialogBOLTab' and (text() = 'BOL #' or . = 'BOL #')]</value>
      <webElementGuid>03673a06-2dd5-41f7-9354-8845a4433332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
