<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Inventories</name>
   <tag></tag>
   <elementGuidId>a6405663-33e2-4cec-842b-38c8cccc00c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.sub-navbar > #inventoriesTab > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='inventoriesTab']/a)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>840a8d93-f8f1-4d7e-a694-d472bb3c8f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>inventory</value>
      <webElementGuid>a68c6636-2d5d-404c-b7ed-15ed34fb3247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inventories</value>
      <webElementGuid>3684ec11-3d5b-455f-94c2-08a80c621125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageWrapper&quot;)/ul[@class=&quot;sub-navbar&quot;]/li[@id=&quot;inventoriesTab&quot;]/a[1]</value>
      <webElementGuid>a4696b90-2ce3-418b-bb2d-b9b629db37e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//li[@id='inventoriesTab']/a)[2]</value>
      <webElementGuid>7321eb13-cdb7-4e28-8487-ee936c90d20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Inventories')])[2]</value>
      <webElementGuid>ce791567-11d0-4387-9073-b8c20afe9256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::a[1]</value>
      <webElementGuid>edf96f6b-acfe-4aac-b859-1d33fff23c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::a[2]</value>
      <webElementGuid>8192407d-ce29-41d6-a59c-8e5b029bb239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity (MC)'])[2]/preceding::a[1]</value>
      <webElementGuid>2b88e515-22c8-4e1a-9b15-e82a7dd3c9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[2]/preceding::a[2]</value>
      <webElementGuid>e24b282b-b994-42c9-a021-0d971cf578c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'inventory')])[2]</value>
      <webElementGuid>054bb8a8-51d0-49bf-a4eb-169146b123aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>90a7a88c-54b3-4dff-a6a7-2043c5f0a531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'inventory' and (text() = 'Inventories' or . = 'Inventories')]</value>
      <webElementGuid>7b017ea7-ff1d-4b85-b519-c53a83facf54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
