<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Request</name>
   <tag></tag>
   <elementGuidId>4bdadc96-72c1-4323-801b-3a287f830c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='searchDialogRequestsRequestTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchDialogRequestsRequestTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2945f4d7-f6bd-4df7-a3ba-7533afb6238d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#requestNumbersRequests</value>
      <webElementGuid>1069ab79-5448-4419-8373-d2aeace7298e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>464090e6-a241-4c05-84f9-187bcd44542e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDialogRequestsRequestTab</value>
      <webElementGuid>60bd9833-0fac-4d9a-9a74-ef1516b11231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request #</value>
      <webElementGuid>05c032fe-31f0-4707-957b-8a1d6096bbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDialogRequestsRequestTab&quot;)</value>
      <webElementGuid>ff31d460-2cd8-4918-8c01-c401c68abfec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='searchDialogRequestsRequestTab']</value>
      <webElementGuid>5c9622b8-c1c8-4161-b6ff-a424ecb409b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchDialogRequests']/div/ul/li[2]/a</value>
      <webElementGuid>80e6cccd-0388-468b-a3c7-179d663894f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Request #')])[2]</value>
      <webElementGuid>2b1098b0-0656-48ce-a6f8-65d181f5e394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REZ Tracking #'])[2]/following::a[1]</value>
      <webElementGuid>3318ba2b-e571-4453-b9c7-b33908340b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Search'])[2]/following::a[2]</value>
      <webElementGuid>5f46d4a8-79a0-46f0-812c-7bdefd2e445a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference #'])[2]/preceding::a[1]</value>
      <webElementGuid>457ec689-d7f9-4618-af1a-2649d2ab905f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#requestNumbersRequests')]</value>
      <webElementGuid>03e58572-ae98-4b61-8d3d-7e622670d6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>25237d99-e81b-45d5-99eb-85b8b65fad0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#requestNumbersRequests' and @id = 'searchDialogRequestsRequestTab' and (text() = 'Request #' or . = 'Request #')]</value>
      <webElementGuid>e40314c4-2d85-4b5b-b751-5d8c39314870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
