<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REZ Tracking</name>
   <tag></tag>
   <elementGuidId>8720d4e1-17bf-479d-9ce1-123120f47a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='searchDialogRequestsTrackingTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchDialogRequestsTrackingTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>721c1767-a460-48c6-8d71-c492ea925a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#trackingNumbersRequests</value>
      <webElementGuid>6bfd3328-714d-4aa5-b26d-dbd13d0d3c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>00346daa-fe8c-4e53-98b2-a6663289730d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDialogRequestsTrackingTab</value>
      <webElementGuid>ecf0f7ba-b023-48f4-a491-54ebffe84052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REZ Tracking #</value>
      <webElementGuid>0809e02d-937f-4d65-ac49-e1738401e48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDialogRequestsTrackingTab&quot;)</value>
      <webElementGuid>491a45c8-5c66-4f5c-943c-742bbfad1e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='searchDialogRequestsTrackingTab']</value>
      <webElementGuid>1e2250d1-e57d-4f26-ba81-3e33f680c030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchDialogRequests']/div/ul/li/a</value>
      <webElementGuid>f87ece1e-fd91-4617-a617-e5182eeeea6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'REZ Tracking #')])[2]</value>
      <webElementGuid>9f74e47c-8759-46b7-b224-731d6ce370ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Search'])[2]/following::a[1]</value>
      <webElementGuid>87e69436-8d58-49ed-bdc2-85f5e4e67186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[10]/following::a[1]</value>
      <webElementGuid>d9a756b3-138a-41eb-a45d-c60ffefda73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request #'])[2]/preceding::a[1]</value>
      <webElementGuid>848898f9-1af2-4667-b5b4-7f16a2bbe2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference #'])[2]/preceding::a[2]</value>
      <webElementGuid>294bd56d-d9d5-4e27-93f6-b65d817bd149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#trackingNumbersRequests')]</value>
      <webElementGuid>0e0cd353-463f-4258-ab35-106faf52d48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div[2]/div/div/ul/li/a</value>
      <webElementGuid>388128f4-d9c6-42c0-966b-2427564edf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#trackingNumbersRequests' and @id = 'searchDialogRequestsTrackingTab' and (text() = 'REZ Tracking #' or . = 'REZ Tracking #')]</value>
      <webElementGuid>4c9a995a-0124-46da-ab3f-8e12ba727865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
