<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reference</name>
   <tag></tag>
   <elementGuidId>ec32ce3a-b174-44a5-9999-458aa340e351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='searchDialogRequestsReferenceTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchDialogRequestsReferenceTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c7b3c7d-8640-486b-a0e5-996064c36027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#referenceNumbersRequests</value>
      <webElementGuid>bfeb56e0-c29d-454d-a244-bc69ea3a9827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f6720549-2f6e-48e9-8240-42831b35dc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDialogRequestsReferenceTab</value>
      <webElementGuid>853b29c0-7ff3-41c0-8a3d-b2e13c2862b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reference #</value>
      <webElementGuid>a1ae04ce-b017-49ba-b354-6d10cc7b1a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDialogRequestsReferenceTab&quot;)</value>
      <webElementGuid>2ddcb060-181a-446b-b764-d4521842339c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='searchDialogRequestsReferenceTab']</value>
      <webElementGuid>c9190ae5-6707-46c0-ba95-b0b981f9e58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchDialogRequests']/div/ul/li[3]/a</value>
      <webElementGuid>84e39f29-5d05-436c-9ba0-5edaf3edc598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Reference #')])[2]</value>
      <webElementGuid>ede95f56-c4b4-4e34-ac04-6743eda51d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request #'])[2]/following::a[1]</value>
      <webElementGuid>07fec82e-2275-4008-8048-853102885059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REZ Tracking #'])[2]/following::a[2]</value>
      <webElementGuid>1f158632-fec6-465b-b59d-9d9aff5eda85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#referenceNumbersRequests')]</value>
      <webElementGuid>b7c417b5-7b1f-4a1f-9123-48179382f171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>b8fc3dd1-a193-4eb7-8d25-9d98c39c8319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#referenceNumbersRequests' and @id = 'searchDialogRequestsReferenceTab' and (text() = 'Reference #' or . = 'Reference #')]</value>
      <webElementGuid>6f7cad20-ad1b-42c3-816e-c9a9626720bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
