<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Waybill</name>
   <tag></tag>
   <elementGuidId>25628e3d-2ab6-4ca5-a284-8988fc6c947f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='searchDialogWaybillTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchDialogWaybillTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b471341a-6ba2-4df6-a095-36a9dad2f1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#waybillNumbersActivity</value>
      <webElementGuid>3f94e6bb-df59-442f-bf6b-3eaea155e7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4fa661e8-7075-41b5-a7e1-bfc98992ff09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDialogWaybillTab</value>
      <webElementGuid>1c3b652e-4ccd-4542-b00f-77464ef83415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Waybill #</value>
      <webElementGuid>7837bb0f-cf43-4ba4-b901-4ce1b48367dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDialogWaybillTab&quot;)</value>
      <webElementGuid>2513c915-189f-4800-8d24-4106dd93b070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='searchDialogWaybillTab']</value>
      <webElementGuid>2b9ddda7-11e9-4ad7-bec3-5306db04ebe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchDialog']/div/ul/li[4]/a</value>
      <webElementGuid>d448fed1-5987-4bdb-bcea-33cc8db73a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Waybill #')]</value>
      <webElementGuid>5e3d2b31-3a42-48de-a82d-e61a49390b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset #'])[1]/following::a[1]</value>
      <webElementGuid>050d0865-b598-4371-a99c-cb8348856727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request #'])[2]/following::a[2]</value>
      <webElementGuid>8e7319f9-624f-420a-ae49-891cf9edeb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference #'])[2]/preceding::a[1]</value>
      <webElementGuid>a2fc5c45-ee6f-4783-b8ce-a41809f4d968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOL #'])[1]/preceding::a[2]</value>
      <webElementGuid>f288c599-31e3-4de4-9476-c97db7768f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Waybill #']/parent::*</value>
      <webElementGuid>683f68f1-40d9-4c23-a059-9b48c3eb852c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#waybillNumbersActivity')]</value>
      <webElementGuid>96410b12-f5ea-4fd1-83d2-0bf181a58cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[2]/div/div/ul/li[4]/a</value>
      <webElementGuid>0807113e-48dd-411f-bd49-29f241aa5518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#waybillNumbersActivity' and @id = 'searchDialogWaybillTab' and (text() = 'Waybill #' or . = 'Waybill #')]</value>
      <webElementGuid>4f52bea6-f75e-4006-9b04-be6510c900bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
