<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Refresh</name>
   <tag></tag>
   <elementGuidId>4cfe914c-84c5-400c-aa6d-4561c58e4902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.always-enabled.refresh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1668134-68ed-4021-8b52-316eb2d8a2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bdaba99-c4af-4f6c-9df0-bbe5ff8a0768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default always-enabled refresh</value>
      <webElementGuid>b5fc18d9-2488-4da6-8d37-371412874398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>dba525ee-f353-425e-8b1b-45788545b271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageWrapper&quot;)/div[@class=&quot;homepage-favorites-table&quot;]/div[@class=&quot;buttons-bar-main&quot;]/div[@class=&quot;btn-group btn-group-sm table-buttons btn-spacer&quot;]/button[@class=&quot;btn btn-default always-enabled refresh&quot;]</value>
      <webElementGuid>4327199b-eeed-48ec-a8f9-cbf9be5c9ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>d8d653b8-45bd-4841-ad18-c41d8d12802d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homePageWrapper']/div[3]/div/div[2]/button</value>
      <webElementGuid>fcb48c8e-18a3-4359-a7a5-24fac7f45619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C H ROBINSON CO'])[1]/following::button[1]</value>
      <webElementGuid>a88bb458-bc36-42f3-967e-f743788cad35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Assets Quick Filters:'])[1]/following::button[1]</value>
      <webElementGuid>059eb003-225e-4954-b250-eaa7a3273817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refresh']/parent::*</value>
      <webElementGuid>2a9ddbdf-9c72-470c-afab-93667cf2466c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button</value>
      <webElementGuid>e9244fd3-12fa-41d7-a709-01e47a76fe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Refresh' or . = 'Refresh')]</value>
      <webElementGuid>584c7db2-0f40-4e99-a1b5-2c53f408c162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
