<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Metro</name>
   <tag></tag>
   <elementGuidId>44eca187-1e05-4396-8d4d-c4cb4c1114ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner'])[2]/following::li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.columns-manager-menu > li:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a7f4901c-dca4-4db9-9756-b74edbdea0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>736c1f85-f8ac-4c36-8232-15cb83ae50f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Metro</value>
      <webElementGuid>1e6b3b94-442f-4ab4-a683-b21da57d4608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open page-overflow&quot;]/div[@class=&quot;modal-scrollable&quot;]/div[@class=&quot;bootstrap modal in&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;columns-manager-menu-container&quot;]/ul[@class=&quot;columns-manager-menu&quot;]/li[4]</value>
      <webElementGuid>809092bb-d642-4500-937f-e9391b555f5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner'])[2]/following::li[1]</value>
      <webElementGuid>965f0e94-cca1-4111-a210-e76b55f1dd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[2]/following::li[2]</value>
      <webElementGuid>b27a5005-4f37-403d-a611-a5a413630862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[2]/preceding::li[1]</value>
      <webElementGuid>b14ccebd-087a-4cae-ad15-5f75e475fc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/ul/li[4]</value>
      <webElementGuid>31984de4-83f2-44d1-98c5-991bd79e7b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Metro' or . = 'Metro')]</value>
      <webElementGuid>70144319-cc8e-4888-bc5e-ad28cb824633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
