<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download template</name>
   <tag></tag>
   <elementGuidId>5aec7700-0dcf-42ca-8a45-700798c0e354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#templateUrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='templateUrl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b21a5618-fae9-4981-a576-4c36f5c44875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>templateUrl</value>
      <webElementGuid>e60a9b07-74d1-4804-be09-b4552b118d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>inventory/getTierUploadTemplate?programCode=MRSK</value>
      <webElementGuid>d1069b09-5f28-4ab6-b859-cf69049ab574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download template</value>
      <webElementGuid>a962ccc1-eefa-470f-9924-1092a2028412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;templateUrl&quot;)</value>
      <webElementGuid>43d0f2b1-a05c-4d65-8773-baf540f69fb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='templateUrl']</value>
      <webElementGuid>7ccee6b0-0a3f-46a4-b8ee-5b81d5639d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='performTierAllotmentUploadDlg']/form/div[2]/div[2]/div/a</value>
      <webElementGuid>ce4ad17c-6ec1-4451-bd08-09b1f47231ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download template')]</value>
      <webElementGuid>c72c7a23-888a-490c-8f67-90c27b52ed27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::a[1]</value>
      <webElementGuid>163e7f42-a86e-4d59-98e1-10e41628b720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::a[1]</value>
      <webElementGuid>e8151b5d-e1c6-4e00-9c70-ee8bb84eec66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download template']/parent::*</value>
      <webElementGuid>f6786d1d-1b3e-4e89-97e8-22dd7f5aae58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'inventory/getTierUploadTemplate?programCode=MRSK')]</value>
      <webElementGuid>53997de4-1db7-4a1c-b166-c1165f3d1a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>9e08044f-500b-484d-9dd1-8fef83c56cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'templateUrl' and @href = 'inventory/getTierUploadTemplate?programCode=MRSK' and (text() = 'Download template' or . = 'Download template')]</value>
      <webElementGuid>970b1e20-7abc-40c7-9253-27b687d4a09e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
