<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Request</name>
   <tag></tag>
   <elementGuidId>2da1aa1f-43a0-4faf-ae08-57465c85b195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.createRequest.yellow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ramp']/div[3]/div[2]/div/div/div[2]/div/button[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4118544e-5a6d-4232-a4a6-8754da2e3c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default createRequest yellow</value>
      <webElementGuid>6ff8c8cf-8a29-4c56-b514-1aeb48e33533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>421d2aeb-6b63-4111-a3b0-76771cb03f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ramp&quot;)/div[@class=&quot;table-area split clearfix&quot;]/div[@class=&quot;top-part&quot;]/div[@class=&quot;pane-wrap clearfix&quot;]/div[@class=&quot;table-actions clearfix&quot;]/div[@class=&quot;buttons-bar-main few-buttons&quot;]/div[@class=&quot;btn-group btn-group-sm btn-spacer&quot;]/button[@class=&quot;btn btn-default createRequest yellow&quot;]</value>
      <webElementGuid>27311257-7547-4bc4-aa9b-0bc3d602e725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ramp']/div[3]/div[2]/div/div/div[2]/div/button[4]</value>
      <webElementGuid>acc83985-e7ef-4ccd-8ea9-d5d068b9487b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Override'])[1]/following::button[2]</value>
      <webElementGuid>49bce1b7-e581-4378-95b6-bce38600d14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Hold'])[1]/preceding::button[1]</value>
      <webElementGuid>4ff9d80a-5a58-41a1-8a9b-18f6c87c65c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allotment'])[1]/preceding::button[2]</value>
      <webElementGuid>3d7e52e1-4bbb-4658-831c-baf6ee8e2412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request']/parent::*</value>
      <webElementGuid>8a623dec-b053-4898-8d83-5287a08cf2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>b81c484e-5a6a-427a-9433-73ae2c4c7643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Request' or . = 'Request')]</value>
      <webElementGuid>d91c35bc-70ea-422b-ab2b-e2a558e93ef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
