<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>87e2e6bf-f8a1-4cfa-a504-37c9e44a28ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bootstrap.modal.in > div.modal-footer > div.modal-buttons-wrap.wrapper-block > #submitButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='submitButton'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2b69409-10f9-4205-bb02-4fffa1f2e3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d346471a-f041-48b4-9fd7-21b355a12689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-next btn-primary pull-right</value>
      <webElementGuid>83adf2f1-fc56-44d6-8ffd-a760642a562d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-last</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>7a580162-0476-4320-b668-aa26373e5043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>dc80193c-8584-46d7-9f48-e066e7c2687d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>bb660c0c-b737-40e4-b31a-54bb61575e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open page-overflow&quot;]/div[@class=&quot;modal-scrollable&quot;]/div[@class=&quot;bootstrap modal in&quot;]/div[@class=&quot;modal-footer&quot;]/div[@class=&quot;modal-buttons-wrap wrapper-block&quot;]/button[@id=&quot;submitButton&quot;]</value>
      <webElementGuid>03741d97-3f0a-4c6a-b851-4a2301b05cbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='submitButton'])[2]</value>
      <webElementGuid>2336b7a9-4bf1-476c-8c37-6ebe76993755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[68]/following::button[1]</value>
      <webElementGuid>7bd27ea7-12cd-4c5d-abc4-a5d0b7a5313e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>7dd01327-a8fa-48a9-8999-505b5c262fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[143]/div/div[3]/div/button[3]</value>
      <webElementGuid>11468f5e-2583-4e7e-8ae9-50d732465afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submitButton' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>97f2e1f8-14b5-4f21-812d-12bf73e16a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitButton']</value>
      <webElementGuid>404a1de6-a7c9-4836-baa0-4a1175728bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[52]/following::button[1]</value>
      <webElementGuid>b45b8640-ab0c-4963-93ff-177245c55f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[3]</value>
      <webElementGuid>0fe37005-0801-4ad5-b79d-4309461b9fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
