<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next_select2-drop-mask</name>
   <tag></tag>
   <elementGuidId>7116e2b9-932f-4b1d-8522-2b3a2dddec44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-drop-mask</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='select2-drop-mask']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b058605-4860-4574-a9ff-2deb92aa63b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-drop-mask</value>
      <webElementGuid>70b8f2e3-ee29-46c2-baf6-8bae944af3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-drop-mask</value>
      <webElementGuid>4668347e-c7e9-403e-afe1-01fccc33d311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-drop-mask&quot;)</value>
      <webElementGuid>b4833455-6e02-405d-aac2-2f8cbc0c6c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='select2-drop-mask']</value>
      <webElementGuid>3dc13045-9932-4681-b8cc-355d79da745d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[145]</value>
      <webElementGuid>eddbed47-757b-4186-9443-9e0a4d3a045e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'select2-drop-mask']</value>
      <webElementGuid>aa823bac-ec68-4b62-98ba-3426f63a91b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[112]</value>
      <webElementGuid>0c094c43-d0d1-4509-a6c6-757015f697dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
