<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Standby</name>
   <tag></tag>
   <elementGuidId>cc598f53-337d-4477-b1c1-ecdf15247dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='todayStandby']/div[2]/div[2]/div/div[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2792ffbf-71cc-4dd8-9dff-c38af10d80a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell even hover</value>
      <webElementGuid>c3abd372-214e-4d3e-a622-707017824f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standby</value>
      <webElementGuid>f18e3a47-951c-4498-afb4-22cf7a2b2cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;todayStandby&quot;)/div[@class=&quot;grid-container yellow multi-select&quot;]/div[@class=&quot;grid-scroll&quot;]/div[@class=&quot;grid-holder&quot;]/div[@class=&quot;column-body&quot;]/div[@class=&quot;cell even hover&quot;]</value>
      <webElementGuid>72418119-c00a-4c43-92a3-47677f00851e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='todayStandby']/div[2]/div[2]/div/div[5]/div</value>
      <webElementGuid>1d5e8677-8f93-483c-8161-cce680e954db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atlanta Sawtell ConGlobal'])[5]/following::div[2]</value>
      <webElementGuid>742d63d4-9034-47d9-a830-7e3e94349804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atlanta Sawtell ConGlobal'])[4]/following::div[3]</value>
      <webElementGuid>4e4f2d2f-e11a-4c77-b69a-0175baad4fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standby'])[2]/preceding::div[1]</value>
      <webElementGuid>b55a21a5-1ec5-402e-b6d4-90d442389668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C H ROBINSON CO'])[1]/preceding::div[8]</value>
      <webElementGuid>7c443f9c-17bb-4998-a3c1-e08290391019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Standby']/parent::*</value>
      <webElementGuid>1ecc9560-af87-42e4-ad96-6304e5cfc620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[2]/div/div[5]/div</value>
      <webElementGuid>68c4972b-dd94-432c-ad1b-13a878b26b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Standby' or . = 'Standby')]</value>
      <webElementGuid>9108cc4c-4e16-48e4-a133-b4e8baaa4ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atlanta Sawtell ConGlobal'])[4]/following::div[2]</value>
      <webElementGuid>80d0bcd8-9cda-401a-9389-8cd2f8471326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alternative Pools'])[1]/following::div[14]</value>
      <webElementGuid>c83b419c-9f47-4f27-957c-502e022ab543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C H ROBINSON CO'])[1]/preceding::div[5]</value>
      <webElementGuid>4ce680a0-c204-456f-bc88-d9e524df8e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VARSHA.SINGH@BLUMEGLOBAL.COM'])[1]/preceding::div[11]</value>
      <webElementGuid>b7c60432-c8ad-4623-82fe-1613a7a0c959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
