<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Program_fa fa-filter</name>
   <tag></tag>
   <elementGuidId>883870e0-88e0-492f-a580-dd5d67f68a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-times</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ramp']/div/div[2]/ul/li[2]/a[3]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8c040d43-0884-4ed0-bc7c-2a95e6bcbba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>6f42c4ee-5e08-4d96-b858-1dfc8eb0b5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ramp&quot;)/div[@class=&quot;quick-filters-area&quot;]/div[@class=&quot;list-group-holder&quot;]/ul[@class=&quot;list-group inventory&quot;]/li[@class=&quot;list-group-item editable selected&quot;]/a[@class=&quot;delete&quot;]/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>a6040866-eeff-43d2-92c7-ff2fc48d4efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ramp']/div/div[2]/ul/li[2]/a[3]/i</value>
      <webElementGuid>7a2b4b5c-014f-4952-883c-12dfee359560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>a68c1993-67f1-4075-a7c6-c067180cc621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ramp']/div/div[2]/ul/li[2]/a[2]/i</value>
      <webElementGuid>14704951-59aa-4dff-a325-7b77272bfed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>355d6f5e-e2e0-4c5e-98ec-f99415d74a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ramp']/div[3]/div[4]/div/div[2]/div/a/i</value>
      <webElementGuid>0043e615-3218-46d3-917d-8d55285531ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>42af498d-f633-43d8-a1b2-eda937142007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ramp']/div[3]/div[4]/div/div[2]/div[2]/a/i</value>
      <webElementGuid>549e0d2c-27e3-4ec3-b90a-c098e3f4521b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>503681bf-06b7-41af-bf9e-493ef9002890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inventory-table']/div/div[2]/a/span/i</value>
      <webElementGuid>6e43390e-f3b3-4522-9c17-9cd4efec66a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>bbd0cc4f-90d4-4510-b9a9-1ceefee2923e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
