<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_View Name_filterName</name>
   <tag></tag>
   <elementGuidId>528de2c4-ab26-4450-a26d-a7d74bafc650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-rename-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-rename-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50f3f465-f4bc-4316-809c-10b379205261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>67c082a0-60e5-4448-bf25-0d87de3cb701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterName</value>
      <webElementGuid>a2900e1a-9ac4-45c0-9de4-2a9449c912cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-rename-field</value>
      <webElementGuid>f30bdc82-63cf-4f10-915d-6b0978c37217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>064e3093-2ce1-42ec-8112-2216b8162bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12299a7b-1b32-4771-8ae4-777c27f50f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>95d7f16a-95ad-413d-b9a7-57361925957e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-rename-field&quot;)</value>
      <webElementGuid>a4c94492-0561-483c-8573-618a9970ecc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-rename-field']</value>
      <webElementGuid>c3ba84d4-e72c-4535-a0ae-1a90545a5ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renameFilterDialog']/div/div/div/input</value>
      <webElementGuid>2e8cf230-8671-4d22-9985-23d897861335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>80b959a3-3750-4402-89e9-cdfe22f6f840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-rename-field' and @name = 'filterName' and @type = 'text']</value>
      <webElementGuid>8ccf119a-501a-47fb-a35d-e3d220f036a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-name-field']</value>
      <webElementGuid>a70d070c-79ff-4990-be41-5ea7ae94aabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nameFilterDialog']/div/div/div/input</value>
      <webElementGuid>cd3d76fb-cae1-47b8-a806-3d2190f213d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'filterName' and @id = 'filter-name-field' and @type = 'text']</value>
      <webElementGuid>6eeef3ea-2320-4697-963d-37d655b3348f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
