<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Invite Users</name>
   <tag></tag>
   <elementGuidId>04766b3c-245a-43eb-8b35-65da2f1e899e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.inviteUsers</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='companyTabs']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db9d769d-3b95-4978-9c50-c398fb7b09aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inviteUsers</value>
      <webElementGuid>6254f34b-c4e0-40b0-a74f-252cc9dddf49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#inviteUsers</value>
      <webElementGuid>78ebd61e-3c8b-47fa-953a-2f891a5c9de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d2322987-b716-46c6-a6f3-6f6d70f3e99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invite Users</value>
      <webElementGuid>500d6183-5736-4062-b804-5e11d946e3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyTabs&quot;)/li[3]/a[@class=&quot;inviteUsers&quot;]</value>
      <webElementGuid>8c11dc42-6ef3-4c4a-a477-cdc928380dcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='companyTabs']/li[3]/a</value>
      <webElementGuid>59232b71-496e-4277-abf8-061478bd53a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Invite Users')]</value>
      <webElementGuid>2f859352-b275-4b95-9516-cb1c01d7823c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[1]</value>
      <webElementGuid>5a1f51f5-1a07-4c50-80ee-9894f13cc837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::a[2]</value>
      <webElementGuid>68e06fcc-d543-4bc6-a279-3bbf5e5f7512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>e24341dc-97c2-478e-b654-a2ad54d91bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::a[1]</value>
      <webElementGuid>37a14ab1-29db-4147-b0e1-0ca6135b4d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invite Users']/parent::*</value>
      <webElementGuid>bae10c1d-6ef5-4b35-9a50-7ce131f3d3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#inviteUsers')]</value>
      <webElementGuid>14864a3a-6711-4850-a773-a1014a3f143a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/a</value>
      <webElementGuid>77fe7923-6fec-40ee-abe3-cf3ce4f1cea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#inviteUsers' and (text() = 'Invite Users' or . = 'Invite Users')]</value>
      <webElementGuid>f437bf1c-2f15-4d7e-b0ff-6b67fba567d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
