<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Impersonate</name>
   <tag></tag>
   <elementGuidId>720b8579-0509-4387-85bc-8bab6588ebbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.impersonateUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='users']/div[2]/div[3]/div[2]/div/button[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>697d5bbd-eee6-4583-a785-4e174dc18090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default impersonateUser</value>
      <webElementGuid>afccbfb8-44f1-45d8-a463-8d82ad0e45b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Impersonate</value>
      <webElementGuid>ff569dff-8ded-4654-8e4e-c98add1d5b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/div[@class=&quot;table-area split clearfix&quot;]/div[@class=&quot;table-actions clearfix&quot;]/div[@class=&quot;buttons-bar-main&quot;]/div[@class=&quot;btn-group btn-group-sm btn-spacer&quot;]/button[@class=&quot;btn btn-default impersonateUser&quot;]</value>
      <webElementGuid>b4045090-48f6-4968-ad08-c55ac16d525e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='users']/div[2]/div[3]/div[2]/div/button[5]</value>
      <webElementGuid>29dc805c-fe2f-45fd-a371-9a17e76739a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/following::button[1]</value>
      <webElementGuid>078998e6-c70f-4b7f-b614-0bcd0e3153f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::button[2]</value>
      <webElementGuid>15a2cb35-4460-4002-af98-19bd07dd6ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear User From Cache'])[1]/preceding::button[1]</value>
      <webElementGuid>2efbb1ea-ed6f-4294-b63e-9e74314ba10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated: 04/24/2023 12:42:21'])[1]/preceding::button[2]</value>
      <webElementGuid>faaeed93-7095-4ee9-8373-df5aa39aabfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Impersonate']/parent::*</value>
      <webElementGuid>57794d80-12cb-4050-9964-75743cd2b0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>e48ae891-baba-4edd-88da-416275be326f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Impersonate' or . = 'Impersonate')]</value>
      <webElementGuid>d9d870db-2065-4aaa-aae3-39ae9e0d8d13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
