<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_chuong.huynhblumeglobal.com</name>
   <tag></tag>
   <elementGuidId>a71827c7-71de-4df1-8c93-ca712c21e712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inviteUsers']/div[2]/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>006afb9f-756c-4cd2-89ca-dab84a5f626b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell even hover</value>
      <webElementGuid>a0f02ce1-ec3c-43b3-895d-29baada8df95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>chuong.huynh@blumeglobal.com</value>
      <webElementGuid>425f29b9-15f2-46e0-b6ce-88e9d386a575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inviteUsers&quot;)/div[@class=&quot;grid-container multi-select&quot;]/div[@class=&quot;grid-scroll&quot;]/div[@class=&quot;grid-holder&quot;]/div[@class=&quot;column-body&quot;]/div[@class=&quot;cell even hover&quot;]</value>
      <webElementGuid>68ed74bc-f70b-4231-b94d-f0eeb365ac67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inviteUsers']/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>6ddcb6dd-b282-42a8-8ecf-4545274ecbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invited By Email'])[1]/following::div[12]</value>
      <webElementGuid>701c338d-50f3-4691-b049-0349d14d8438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Invite Date'])[1]/following::div[16]</value>
      <webElementGuid>9cc4453d-d38d-4866-899e-102042d059b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vinod.kumar@blumeglobal.com'])[1]/preceding::div[1]</value>
      <webElementGuid>fff33964-3774-41ee-a1de-212a7fb4f223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='satish.krishnan@blumeglobal.com'])[1]/preceding::div[2]</value>
      <webElementGuid>bab424bc-f6c8-44a4-a7aa-bf5b05ae45f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='chuong.huynh@blumeglobal.com']/parent::*</value>
      <webElementGuid>eef33d56-a927-4031-9fcf-71a8486c5e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>87d989d3-087d-47c7-9f57-e2c8b3c3381d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'chuong.huynh@blumeglobal.com' or . = 'chuong.huynh@blumeglobal.com')]</value>
      <webElementGuid>052487fe-b7f2-42bd-a51b-3b732484f1d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
