<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Don, , t ask me again for the _2963e3</name>
   <tag></tag>
   <elementGuidId>9477629d-23d4-45ec-af9d-d0e3b95a15b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.tfa-blue-button-enabled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0be7189f-3afb-4175-9edc-de38c6027092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tfa-blue-button-enabled</value>
      <webElementGuid>77f77e1a-0cf6-4fa8-9a1e-82dc6698bb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>503a8899-29c0-4e7a-9207-6613b1071f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2cd8f03c-dfed-4011-b5d6-cbd16638b2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>26b7a22f-2d0f-4745-b2f5-02d40b8f2061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;twofaOtpForm&quot;)/div[@class=&quot;tfa-ns-footer&quot;]/div[@class=&quot;tfa-verify-footer-login&quot;]/input[@class=&quot;tfa-blue-button-enabled&quot;]</value>
      <webElementGuid>f318ddd5-d8a2-46ec-ac73-574a02e1940c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Login']</value>
      <webElementGuid>85592724-83e3-40ec-9ae4-461ea6ecaa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='twofaOtpForm']/div[7]/div/input</value>
      <webElementGuid>8cfe52dc-b8ef-4958-a195-4351f5142dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>5e81187d-e529-40f6-a268-b39939d8cb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>7606c4ff-14b2-4344-9ec3-97a4eb89e2dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
