<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Verification Code_oneTimePassword</name>
   <tag></tag>
   <elementGuidId>f4c9f91e-d96b-46b1-8fa8-7176c8bf579a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;oneTimePassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='oneTimePassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>064dbeef-2368-471e-bd33-e2e3ceee874e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oneTimePassword</value>
      <webElementGuid>acd7fb75-98b9-498f-a9de-3d4214401426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input</value>
      <webElementGuid>b1c3178f-d40c-4ff3-b95a-e590bb82c143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f39d475-151b-422a-b8da-340596dc3a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>e8b12fc9-912c-484b-ab24-d902ecc7e316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8df5c88f-4c2c-4ff0-b226-0afd34d0a638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d2515f8-7200-41d9-8aff-15860e9c3494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{6}</value>
      <webElementGuid>9e3b4f8c-13f4-4321-ac34-559e6e69d6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(this.value.length==6) return false;</value>
      <webElementGuid>29c9e520-8734-4a90-9f17-8fe7e9601afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase();</value>
      <webElementGuid>85036e9e-32c0-42d8-90a7-da10ea0d2a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;twofaOtpForm&quot;)/div[@class=&quot;otp-container&quot;]/div[@class=&quot;otp-box&quot;]/input[@class=&quot;otp-input&quot;]</value>
      <webElementGuid>5f837394-c79b-45fe-8533-cc307e127c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='oneTimePassword']</value>
      <webElementGuid>b02d3e17-83d8-45c7-8494-f7208002cbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='twofaOtpForm']/div[5]/div/input</value>
      <webElementGuid>ebc7e9c6-2ece-4b5d-b82e-b3ba2ea70b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3830e6d0-e82c-439e-8fa5-159d773d4bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'oneTimePassword' and @type = 'text']</value>
      <webElementGuid>6d5e0213-7203-48aa-b5e5-f6793897696b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
